/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudusuarios;

import auxClass.systemConf;
import auxClass.Users;
import static crudusuarios.LoginForm.container;
import static crudusuarios.LoginForm.lg;
import java.awt.Color;
import java.awt.FlowLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author Akme
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents(); 
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginView = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        btn_SignIn = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();
        txt_pass = new javax.swing.JPasswordField();
        RegisterView = new javax.swing.JPanel();

        setBackground(new java.awt.Color(200, 245, 233));
        setPreferredSize(new java.awt.Dimension(440, 799));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginView.setBackground(new java.awt.Color(255, 255, 255));
        LoginView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(126, 125, 125));
        jLabel1.setText("LOGIN");
        LoginView.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        txt_username.setBackground(new java.awt.Color(225, 225, 225));
        txt_username.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txt_username.setForeground(new java.awt.Color(126, 125, 125));
        txt_username.setText("Pepito56");
        txt_username.setToolTipText("Username");
        txt_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_usernameMouseClicked(evt);
            }
        });
        LoginView.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 251, 38));

        btn_SignIn.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_SignIn.setForeground(new java.awt.Color(126, 125, 125));
        btn_SignIn.setText("Sign In");
        btn_SignIn.setBorder(null);
        btn_SignIn.setFocusable(false);
        btn_SignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SignInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SignInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SignInMouseExited(evt);
            }
        });
        LoginView.add(btn_SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 151, 38));

        btn_register.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_register.setForeground(new java.awt.Color(126, 125, 125));
        btn_register.setText("Register");
        btn_register.setBorder(null);
        btn_register.setFocusable(false);
        btn_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registerMouseExited(evt);
            }
        });
        LoginView.add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 151, 38));

        txt_pass.setBackground(new java.awt.Color(225, 225, 225));
        txt_pass.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(126, 125, 125));
        txt_pass.setText("PepitoElGrillo");
        txt_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_passMouseClicked(evt);
            }
        });
        LoginView.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 251, 38));

        add(LoginView, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 272, 300));

        RegisterView.setBackground(new java.awt.Color(200, 245, 233));
        RegisterView.setAlignmentX(0.0F);
        RegisterView.setAlignmentY(0.0F);
        RegisterView.setLayout(new javax.swing.BoxLayout(RegisterView, javax.swing.BoxLayout.LINE_AXIS));
        add(RegisterView, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 460, 780));
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean validateTxtFields(){  
        return (String.valueOf(txt_pass.getPassword()).length() == 0) || (txt_username.getText().length() == 0);
    }
    
    private void btn_SignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SignInMouseEntered
        btn_SignIn.setBackground(new Color(106, 197, 127));
        btn_SignIn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btn_SignInMouseEntered

    private void btn_SignInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SignInMouseExited
        btn_SignIn.setBackground(new Color(255,255,255));
        btn_SignIn.setForeground(new Color(126,125,125));
    }//GEN-LAST:event_btn_SignInMouseExited

    private void btn_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registerMouseClicked
        RegisterView.removeAll();
        LoginView.removeAll();
        RegisterView.revalidate();
        LoginView.revalidate();
        
        RegisterView.setLayout(new FlowLayout());
        
        RegisterView.add(new RegisterPanel());
        //LoginView.setVisible(false);
        RegisterView.setVisible(true);
        
        //RegisterView.removeAll();
        LoginView.removeAll();
        LoginView.setLayout(new FlowLayout());
       // JOptionPane.showMessageDialog(null, LoginView.getComponentCount() + " -- " + RegisterView.getComponentCount());
    }//GEN-LAST:event_btn_registerMouseClicked

    private void btn_registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registerMouseEntered
        btn_register.setBackground(new Color(106, 197, 127));
        btn_register.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btn_registerMouseEntered

    private void btn_registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registerMouseExited
        btn_register.setBackground(new Color(255,255,255));
        btn_register.setForeground(new Color(126,125,125));
    }//GEN-LAST:event_btn_registerMouseExited

    private void txt_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usernameMouseClicked
        txt_username.setText("");
    }//GEN-LAST:event_txt_usernameMouseClicked

    private void btn_SignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SignInMouseClicked
        systemConf sys = new systemConf();
           
        if(this.validateTxtFields()){
            JOptionPane.showMessageDialog(null, "Campos vacios");
        }else try(ResultSet rs = sys.selectData(generateSQLCode())) {
            
            if(!rs.isClosed()){
                
                sys.createSession(generateSession(rs));
                
                Principal pView = new Principal();
                
                lg.setVisible(false);
                
                pView.setVisible(true);
                
                rs.close();
                
            }else{
                JOptionPane.showMessageDialog(null, "El usuario no existe");
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            sys.closeConnection();
        } catch (SQLException ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_SignInMouseClicked
    
    private Users generateSession(ResultSet info) throws SQLException{
        return new Users(
                Integer.parseInt(info.getString("id")),
                info.getString("name"),
                info.getString("lastname"),
                info.getString("username"),
                info.getString("phone"),
                info.getString("email"),
                new String(txt_pass.getPassword())
        );
    }
    
    private String generateSQLCode(){
        
        String pass = new String(txt_pass.getPassword());
        
        String sql = String.format("select * from users where username = '%s' and password = '%s'",
                txt_username.getText(), pass);
        
        return sql;
    }
    
    private void txt_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passMouseClicked
        txt_pass.setText("");
    }//GEN-LAST:event_txt_passMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginView;
    private javax.swing.JPanel RegisterView;
    private javax.swing.JButton btn_SignIn;
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
