/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudusuarios;

import auxClass.systemConf;
import java.awt.FlowLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Akme
 */
public class RegisterPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterPanel
     */
    
    //LoginPanel lPanel = new LoginPanel();
    
    public RegisterPanel() {
        initComponents();
        
    }
    
    public void register(){
        LoginView2.add(new LoginPanel());
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    
    private boolean getBooleanOfFields(javax.swing.JTextField txt){
        return txt.getText().length() == 0;
    }
    
    private boolean getBooleanOfFields(javax.swing.JPasswordField pass){
        return String.valueOf(pass.getPassword()).length() == 0;
    }
    
    private boolean validatePasswords(){
        return String.valueOf(txt_confPass.getPassword()).equals(String.valueOf(txt_pass.getPassword()));
    }
    
    private boolean validateFields(){
        
        boolean userName = getBooleanOfFields(txt_user), 
                name = getBooleanOfFields(txt_name), 
                lastName = getBooleanOfFields(txt_lastName), 
                phone = getBooleanOfFields(txt_Phone), 
                email = getBooleanOfFields(txt_email), 
                pass = getBooleanOfFields(txt_pass), 
                confPass = (String.valueOf(txt_confPass.getPassword()).length() == 0);
         
        return userName || name || lastName || phone || email || pass || confPass;
    }
       
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RegisterView2 = new javax.swing.JPanel();
        txt_user = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_lastName = new javax.swing.JTextField();
        txt_Phone = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txt_pass = new javax.swing.JPasswordField();
        txt_confPass = new javax.swing.JPasswordField();
        btn_cancel = new javax.swing.JButton();
        LoginView2 = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(200, 245, 233));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegisterView2.setBackground(new java.awt.Color(255, 255, 255));
        RegisterView2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_user.setBackground(new java.awt.Color(225, 225, 225));
        txt_user.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_user.setForeground(new java.awt.Color(126, 125, 125));
        txt_user.setText("  Username");
        txt_user.setToolTipText("Insert username");
        txt_user.setActionCommand("<Not Set>");
        txt_user.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_userMouseClicked(evt);
            }
        });
        RegisterView2.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 251, 38));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(126, 125, 125));
        jLabel1.setText("REGISTER");
        RegisterView2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        txt_name.setBackground(new java.awt.Color(225, 225, 225));
        txt_name.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_name.setForeground(new java.awt.Color(126, 125, 125));
        txt_name.setText("  Name");
        txt_name.setToolTipText("Insert name");
        txt_name.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_nameMouseClicked(evt);
            }
        });
        RegisterView2.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 251, 38));

        txt_lastName.setBackground(new java.awt.Color(225, 225, 225));
        txt_lastName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_lastName.setForeground(new java.awt.Color(126, 125, 125));
        txt_lastName.setText("  Last name");
        txt_lastName.setToolTipText("Insert last name");
        txt_lastName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_lastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_lastNameMouseClicked(evt);
            }
        });
        RegisterView2.add(txt_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 251, 38));

        txt_Phone.setBackground(new java.awt.Color(225, 225, 225));
        txt_Phone.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_Phone.setForeground(new java.awt.Color(126, 125, 125));
        txt_Phone.setText("  Phone");
        txt_Phone.setToolTipText("Insert phone");
        txt_Phone.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_Phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_PhoneMouseClicked(evt);
            }
        });
        RegisterView2.add(txt_Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 251, 38));

        txt_email.setBackground(new java.awt.Color(225, 225, 225));
        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_email.setForeground(new java.awt.Color(126, 125, 125));
        txt_email.setText("  Email");
        txt_email.setToolTipText("Insert email");
        txt_email.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_emailMouseClicked(evt);
            }
        });
        RegisterView2.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 251, 38));

        jButton1.setBackground(new java.awt.Color(112, 216, 136));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Register");
        jButton1.setFocusable(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        RegisterView2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 460, 120, 38));

        txt_pass.setBackground(new java.awt.Color(225, 225, 225));
        txt_pass.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(126, 125, 125));
        txt_pass.setText("  Password");
        txt_pass.setToolTipText("Insert password");
        txt_pass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_passMouseClicked(evt);
            }
        });
        RegisterView2.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 251, 38));

        txt_confPass.setBackground(new java.awt.Color(225, 225, 225));
        txt_confPass.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_confPass.setForeground(new java.awt.Color(126, 125, 125));
        txt_confPass.setText("  Password");
        txt_confPass.setToolTipText("Confirm password");
        txt_confPass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_confPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_confPassMouseClicked(evt);
            }
        });
        RegisterView2.add(txt_confPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 251, 38));

        btn_cancel.setBackground(new java.awt.Color(217, 12, 12));
        btn_cancel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setText("Cancel");
        btn_cancel.setFocusable(false);
        btn_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelMouseClicked(evt);
            }
        });
        RegisterView2.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 120, 38));

        jPanel1.add(RegisterView2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 272, 520));

        LoginView2.setBackground(new java.awt.Color(200, 245, 233));
        LoginView2.setAlignmentX(0.0F);
        LoginView2.setLayout(new javax.swing.BoxLayout(LoginView2, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(LoginView2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 550));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_userMouseClicked
        txt_user.setText("");
    }//GEN-LAST:event_txt_userMouseClicked

    private void txt_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nameMouseClicked
        txt_name.setText("");
    }//GEN-LAST:event_txt_nameMouseClicked

    private void txt_lastNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_lastNameMouseClicked
        txt_lastName.setText("");
    }//GEN-LAST:event_txt_lastNameMouseClicked

    private void txt_PhoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_PhoneMouseClicked
        txt_Phone.setText("");
    }//GEN-LAST:event_txt_PhoneMouseClicked

    private void txt_emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_emailMouseClicked
        txt_email.setText("");
    }//GEN-LAST:event_txt_emailMouseClicked

    private void txt_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passMouseClicked
        txt_pass.setText("");
    }//GEN-LAST:event_txt_passMouseClicked

    private void txt_confPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_confPassMouseClicked
        txt_confPass.setText("");
    }//GEN-LAST:event_txt_confPassMouseClicked

    private void btn_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseClicked
        LoginView2.removeAll();
        RegisterView2.removeAll();
        RegisterView2.revalidate();
        
        LoginView2.setLayout(new FlowLayout());
        
        LoginView2.add(new LoginPanel());
       // RegisterView2.setVisible(false);
        LoginView2.setVisible(true);
        
        //LoginView2.removeAll();
        RegisterView2.removeAll();
        
        RegisterView2.setLayout(new FlowLayout());
        //JOptionPane.showMessageDialog(null, LoginView2.getComponentCount() + " -- " + RegisterView2.getComponentCount());
    }//GEN-LAST:event_btn_cancelMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        systemConf sys = new systemConf();
        
        if(validateFields()){
            
            JOptionPane.showMessageDialog(null, "Vacio");
            
        }else if(!validatePasswords()){
            
            JOptionPane.showMessageDialog(null, "Las contrasenas no concuerdan");
        }else{
            
            try {
                
                sys.insertData(generateSQLCode());
                
            } catch (SQLException ex) {
                
                Logger.getLogger(RegisterPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        try {
            sys.closeConnection();
        } catch (SQLException ex) {
            Logger.getLogger(RegisterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        cleanFlieds();
        
    }//GEN-LAST:event_jButton1MouseClicked
    
    private void cleanFlieds(){
        txt_name.setText("");
        txt_pass.setText("");
        txt_user.setText("");
        txt_lastName.setText("");
        txt_confPass.setText("");
        txt_Phone.setText("");
        txt_email.setText("");
    }
    
    private String generateSQLCode(){
        
        String pass = new String(txt_pass.getPassword());
        
        String sql = String.format("insert into users('name', 'password', 'lastname', 'username', 'phone', 'email')" +
                                    "values('%s', '%s', '%s', '%s', '%s', '%s');",
                                    txt_name.getText(), pass, txt_lastName.getText(), txt_user.getText(), txt_Phone.getText(), txt_email.getText());
        
        return sql;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginView2;
    private javax.swing.JPanel RegisterView2;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_Phone;
    private javax.swing.JPasswordField txt_confPass;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}


